"""GNW Trace Evaluation Utilities."""

from utils.langfuse_api import (
    get_langfuse_headers,
    get_annotation_queue_item,
    get_annotation_queue,
    list_annotation_queue_items,
    fetch_trace,
    fetch_traces_window,
    fetch_user_first_seen,
    invalidate_user_first_seen_cache,
    extract_datasets_from_session,
    fetch_score_configs,
    fetch_scores_by_queue,
    list_annotation_queues,
    create_annotation_queue,
    create_annotation_queue_item,
    update_annotation_queue_item,
    fetch_projects,
    create_score,
    delete_score,
)
from utils.trace_parsing import (
    normalize_trace_format,
    parse_trace_dt,
    first_human_prompt,
    final_ai_message,
    current_human_prompt,
    current_turn_ai_message,
    slice_output_to_current_turn,
    current_turn_prompt_answer,
    classify_outcome,
    extract_trace_context,
    extract_tool_calls_and_results,
    extract_tool_flow,
    extract_usage_metadata,
    trace_has_internal_error,
)
from utils.data_helpers import (
    maybe_load_dotenv,
    iso_utc,
    as_float,
    strip_code_fences,
    safe_json_loads,
    csv_bytes_any,
    init_session_state,
)
from utils.llm_helpers import (
    get_gemini_model_options,
    chunked,
    truncate_text,
    parse_json_any,
    parse_json_dict,
    call_gemini,
)
from utils.shared_ui import (
    check_authentication,
    render_sidebar,
    get_app_config,
    configure_page,
)
from utils.charts import (
    daily_volume_chart,
    daily_outcome_chart,
    daily_cost_chart,
    daily_latency_chart,
    outcome_pie_chart,
    language_bar_chart,
    latency_histogram,
    cost_histogram,
    category_pie_chart,
    success_rate_bar_chart,
    tool_success_rate_chart,
    tool_calls_vs_latency_chart,
    reasoning_tokens_histogram,
    tool_flow_sankey_data,
    tool_flow_arc_chart,
)
from utils.content_kpis import (
    compute_derived_interactions,
    summarize_content,
    build_content_slices,
)
from utils.eval_sampling import (
    SAMPLE_PRESETS,
    build_preset_mask,
    apply_candidate_filters,
    sample_trace_ids,
)

__all__ = [
    # Langfuse API
    "get_langfuse_headers",
    "get_annotation_queue_item",
    "get_annotation_queue",
    "list_annotation_queue_items",
    "fetch_trace",
    "fetch_traces_window",
    "fetch_user_first_seen",
    "invalidate_user_first_seen_cache",
    "extract_datasets_from_session",
    "fetch_score_configs",
    "fetch_scores_by_queue",
    "list_annotation_queues",
    "create_annotation_queue",
    "create_annotation_queue_item",
    "update_annotation_queue_item",
    "fetch_projects",
    "create_score",
    "delete_score",
    # Trace parsing
    "normalize_trace_format",
    "parse_trace_dt",
    "first_human_prompt",
    "final_ai_message",
    "current_human_prompt",
    "current_turn_ai_message",
    "slice_output_to_current_turn",
    "current_turn_prompt_answer",
    "classify_outcome",
    "extract_trace_context",
    "extract_tool_calls_and_results",
    "extract_tool_flow",
    "extract_usage_metadata",
    "trace_has_internal_error",
    # Data helpers
    "maybe_load_dotenv",
    "iso_utc",
    "as_float",
    "strip_code_fences",
    "safe_json_loads",
    "csv_bytes_any",
    "init_session_state",
    # LLM helpers
    "get_gemini_model_options",
    "chunked",
    "truncate_text",
    "parse_json_any",
    "parse_json_dict",
    "call_gemini",
    # Charts
    "daily_volume_chart",
    "daily_outcome_chart",
    "daily_cost_chart",
    "daily_latency_chart",
    "outcome_pie_chart",
    "language_bar_chart",
    "latency_histogram",
    "cost_histogram",
    "category_pie_chart",
    "success_rate_bar_chart",
    "tool_success_rate_chart",
    "tool_calls_vs_latency_chart",
    "reasoning_tokens_histogram",
    "tool_flow_sankey_data",
    "tool_flow_arc_chart",
    # Content KPIs
    "compute_derived_interactions",
    "summarize_content",
    "build_content_slices",
    # Eval sampling
    "SAMPLE_PRESETS",
    "build_preset_mask",
    "apply_candidate_filters",
    "sample_trace_ids",
    # Shared UI
    "check_authentication",
    "render_sidebar",
    "get_app_config",
    "configure_page",
]
