"""GNW Trace Evaluation Utilities."""

from utils.fetch_throttle import (
    TokenBucket,
    SharedBudget,
)
from utils.langfuse_api import (
    get_langfuse_headers,
    get_annotation_queue_item,
    get_annotation_queue,
    list_annotation_queue_items,
    fetch_trace,
    fetch_traces_window,
    fetch_user_first_seen,
    invalidate_user_first_seen_cache,
    extract_datasets_from_session,
    fetch_score_configs,
    fetch_scores_by_queue,
    list_annotation_queues,
    create_annotation_queue,
    create_annotation_queue_item,
    update_annotation_queue_item,
    fetch_projects,
    create_score,
    delete_score,
)
from utils.trace_parsing import (
    normalize_trace_format,
    parse_trace_dt,
    first_human_prompt,
    final_ai_message,
    active_turn_prompt,
    active_turn_answer,
    classify_outcome,
    extract_trace_context,
    extract_tool_calls_and_results,
    extract_tool_flow,
    extract_usage_metadata,
    trace_has_internal_error,
)
from utils.data_helpers import (
    maybe_load_dotenv,
    iso_utc,
    as_float,
    strip_code_fences,
    safe_json_loads,
    csv_bytes_any,
    init_session_state,
    format_report_date,
    normalize_prompt,
    safe_quantile,
)
from utils.enrichment_schema import (
    TraceEnrichment,
    TraceEnrichmentWithId,
    BatchEnrichmentResponse,
    enrichment_json_schema,
    batch_enrichment_json_schema,
    validate_enrichment,
    validate_batch_enrichment,
    coerce_enrichment,
    is_welcome_prompt,
    load_starter_prompts,
    load_dataset_catalog,
    dataset_catalog_keywords,
    dataset_catalog_summary,
)
from utils.llm_helpers import (
    get_gemini_model_options,
    chunked,
    truncate_text,
    parse_json_any,
    parse_json_dict,
    call_gemini,
    call_gemini_structured,
    model_aware_batch_size,
)
from utils.shared_ui import (
    check_authentication,
    render_sidebar,
    get_app_config,
    configure_page,
)
from utils.user_segments import (
    compute_engaged_users,
    build_first_seen_lookup,
    classify_user_segments,
    build_daily_user_segments,
    UserSegments,
)
from utils.charts import (
    daily_volume_chart,
    daily_outcome_chart,
    daily_cost_chart,
    daily_latency_chart,
    outcome_pie_chart,
    language_bar_chart,
    latency_histogram,
    cost_histogram,
    category_pie_chart,
    success_rate_bar_chart,
    tool_success_rate_chart,
    tool_calls_vs_latency_chart,
    reasoning_tokens_histogram,
    tool_flow_sankey_data,
    tool_flow_arc_chart,
    dynamic_bar_height,
    prompt_utilisation_histogram,
    prompt_utilisation_daily_chart,
    user_segment_bar_chart,
    user_segment_pie_chart,
    starter_vs_other_pie,
    starter_breakdown_pie,
    prompt_length_histogram,
    aoi_type_pie,
    aoi_name_bar,
    simple_pie_chart,
)

__all__ = [
    # Fetch throttle
    "TokenBucket",
    "SharedBudget",
    # Langfuse API
    "get_langfuse_headers",
    "get_annotation_queue_item",
    "get_annotation_queue",
    "list_annotation_queue_items",
    "fetch_trace",
    "fetch_traces_window",
    "fetch_user_first_seen",
    "invalidate_user_first_seen_cache",
    "extract_datasets_from_session",
    "fetch_score_configs",
    "fetch_scores_by_queue",
    "list_annotation_queues",
    "create_annotation_queue",
    "create_annotation_queue_item",
    "update_annotation_queue_item",
    "fetch_projects",
    "create_score",
    "delete_score",
    # Trace parsing
    "normalize_trace_format",
    "parse_trace_dt",
    "first_human_prompt",
    "final_ai_message",
    "active_turn_prompt",
    "active_turn_answer",
    "classify_outcome",
    "extract_trace_context",
    "extract_tool_calls_and_results",
    "extract_tool_flow",
    "extract_usage_metadata",
    "trace_has_internal_error",
    # Data helpers
    "maybe_load_dotenv",
    "iso_utc",
    "as_float",
    "strip_code_fences",
    "safe_json_loads",
    "csv_bytes_any",
    "init_session_state",
    "format_report_date",
    "normalize_prompt",
    "safe_quantile",
    # Enrichment schema
    "TraceEnrichment",
    "TraceEnrichmentWithId",
    "BatchEnrichmentResponse",
    "enrichment_json_schema",
    "batch_enrichment_json_schema",
    "validate_enrichment",
    "validate_batch_enrichment",
    "coerce_enrichment",
    "is_welcome_prompt",
    "load_starter_prompts",
    "load_dataset_catalog",
    "dataset_catalog_keywords",
    "dataset_catalog_summary",
    # LLM helpers
    "get_gemini_model_options",
    "chunked",
    "truncate_text",
    "parse_json_any",
    "parse_json_dict",
    "call_gemini",
    "call_gemini_structured",
    "model_aware_batch_size",
    # Charts
    "daily_volume_chart",
    "daily_outcome_chart",
    "daily_cost_chart",
    "daily_latency_chart",
    "outcome_pie_chart",
    "language_bar_chart",
    "latency_histogram",
    "cost_histogram",
    "category_pie_chart",
    "success_rate_bar_chart",
    "tool_success_rate_chart",
    "tool_calls_vs_latency_chart",
    "reasoning_tokens_histogram",
    "tool_flow_sankey_data",
    "tool_flow_arc_chart",
    "dynamic_bar_height",
    "prompt_utilisation_histogram",
    "prompt_utilisation_daily_chart",
    "user_segment_bar_chart",
    "user_segment_pie_chart",
    "starter_vs_other_pie",
    "starter_breakdown_pie",
    "prompt_length_histogram",
    "aoi_type_pie",
    "aoi_name_bar",
    "simple_pie_chart",
    # Shared UI
    "check_authentication",
    "render_sidebar",
    "get_app_config",
    "configure_page",
    # User segments
    "compute_engaged_users",
    "build_first_seen_lookup",
    "classify_user_segments",
    "build_daily_user_segments",
    "UserSegments",
]
